### ISSUE TITLE
Changing floated element crashes jQuery

### ISSUE THREAD

**Issue by midjord** [gilly3/lowFloat#1]
I needed to change how the floated element looked in a different @media interval. The CSS I applied was: float: none; width: 100%; clear: both;
This change crashes jQuery in Firefox, Internet Explorer and Chrome. Please advice :)

**Comment by gilly3** [comment]
Can you provide a jsfiddle demo, or at least some minimal code?  I tried, but this doesn't crash jQuery for me:  http://jsfiddle.net/n5RPV/82/

**Comment by midjord** [comment]
I'm sorry, I forgot to mention that I also change the div's height to 0 via CSS: height: 0 !important, to have the box at the top in mobile view.

**Comment by gilly3** [comment]
I'm sorry, I don't follow.  Can you post some code that demonstrates jQuery crashing?  Perhaps you can update [my jsfiddle](http://jsfiddle.net/n5RPV/82/) and post a link here to your updated jsfiddle that crashes jQuery.

**Comment by midjord** [comment]
http://jsfiddle.net/n5RPV/88/ - I've added "div { width: 100% !important }" in the CSS
Edit: It should of course have been height, but it seems to fail regardless.

**Comment by gilly3** [comment]
Ok, I see it now.  What we have is an infinite loop.  The plugin tries to increase the height of the spacer until it pushes the floater low enough.  But, when you force the spacer height to zero, it never gets there and just keeps looping.

So, don't override the spacer height with CSS.  Instead, we will have to modify the plugin to give it a way to turn it off.

**Comment by gilly3** [comment]
Ok, I pushed an update (04237f58955c04abd723e129788c30c320393713) that does two things:
1. Add a class to the spacer: `lowFloat-spacer`.  This way, you can use CSS to easily target the spacer.
2. Prevent resizing the spacer if its `display` is set to anything but `block`.  I had wanted to check `.is(":visible")` here, but this always returns `false` because it is `0px` wide.  (This behavior changes in jQuery 3.0.0)

So, to disable lowFloat, set `display: none` on `.lowFloat-spacer`:

``` css
@media (max-width: 400px) {
    .lowFloat-spacer {
        display: none;
    }
}
```

http://jsfiddle.net/n5RPV/90/

**Comment by midjord** [comment]
That is awesome, thank you! :+1:
